version: '3.7'

services:
  # Conteneur applicatif (site wordpress)
  # Exposé sur le port 80 de l'hôte
  # Même réseau que la base et phpmyadmin
  wordpress:
    hostname: wp.local
    image: wordpress:latest
    ports:
    # host_port:container_port
        - "8082:80"
    # restart: always
    env_file: 
      - ./wp-env.env
    volumes:
    # host_volume:container_volume
    # La partie web contient l'ensemble du code wordpress de notre application. Il n'est pas utile
    # de le synchroniser à la seconde car il n'y aura des modifications qu'à la mise à jour mais
    # ces fichiers représentent un gros volume.
      - ../:/var/www/html:rw,delegated
    # Seuls ces deux répertoires représentent notre code custom et demandent plus de réactivité.
      - ../wp-content/plugins:/var/www/html/wp-content/plugins:rw,cached
      - ../wp-content/themes:/var/www/html/wp-content/themes:rw,cached
    networks:
      - wp_network

  # Conteneur de base de données
  # Même réseau que l'application et PHPMyAdmin
  # Pas de port exposé
  wp_mysql:
    image: mysql:5.7
    # restart: always
    # volumes:
    #    - ./db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: secret
    networks: 
      - wp_network

  # Conteneur PHPMyAdmin (2ème site exposé sur le port 8080)
  # Même réseau que l'applicatif et la base de données
  wp_phpmyadmin:
    hostname: wp_pma.local
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
        - "8083:80"
    environment:
      PMA_HOST: wp_mysql
    networks: 
      - wp_network

networks:
  wp_network:
    driver: bridge